### ISSUE TITLE
Db name changing

### ISSUE THREAD

**Issue by TeodorKolev** [zacfukuda/graphql-mongo#1]
Why server returns no results if I use another db. It works only if db name is 'graphql'. Can I change that?

**Comment by zacfukuda** [comment]
Hi TeodorKolev,

Thank you for bringing up the issue.
You can change the name of database modifying `config.js` located each of `Basic`, `Express`, `React` folders. (In `React.js`, it is located in `React > server`.)

And do not forget to seed new data when you change the name of db.
Hope this helps you.

**Comment by TeodorKolev** [comment]
Sounds good, doesn't work

**Comment by zacfukuda** [comment]
If you give me more details such as which version of Node or MongoDB you are using or what kind of error message you see in Terminal or Browser console, I appreciate it. Otherwise I cannot help you.

**Comment by TeodorKolev** [comment]
Sure there is no such errors, just it returns empty response. Steps to reproduce: run seed, run app, stop app change db and collection name from config, run seed. New db is filled, but when access for example books - it returns empty array

**Comment by zacfukuda** [comment]
When you say “New db is filled,” are you sure that new data is generated in MongoDB? Did you check it via Mongo CLI?

And did you try `mutation` as well to generate new data? If you have connection to DB successfully through the app, at least you can `Query` data generated with mutation.

And your MongoDB version?

**Comment by TeodorKolev** [comment]
Data is 100% generated. My code:
```
module.exports = {
  dbURL: 'mongodb://localhost:27017',
  dbName: 'something',
  collectionName: 'anotherthing'
}
```
seed - success,
db version 3.4.7

**Comment by zacfukuda** [comment]
Hi TeodorKolev,

I found out why it returns nothing.
The app uses Mongoose to make it easy to read data from the database. And Mongoose by default looks for collection in plural name from database. For example. in our case we define `Book` model, and Mongoose looks for collection named `books`.

That’s why when you change the name of collection to other than `books`, it returns no data.
Please check out their official doc at http://mongoosejs.com/docs/models.html#compiling, or find a concrete solution at https://stackoverflow.com/questions/7486528/mongoose-force-collection-name if you want to use other than `books` collection name.

**Comment by TeodorKolev** [comment]
Good catch dude! Thanks. I wish I would overcome that, but I will search for it later. Thanks again
